-- MySQL Script generated by MySQL Workbench
-- Thu May  7 12:33:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema misdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `misdb` ;

-- -----------------------------------------------------
-- Schema misdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `misdb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `misdb` ;

-- -----------------------------------------------------
-- Table `misdb`.`authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`authentication` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`authentication` (
                                                       `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `user_name` VARCHAR(45) NULL,
                                                       `password_hash` VARCHAR(45) NULL,
                                                       PRIMARY KEY (`id`))
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`contact` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`contact` (
                                                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                `first` VARCHAR(45) NULL,
                                                `goverment_id` VARCHAR(45) NULL,
                                                `primary_email` VARCHAR(255) NULL,
                                                `primary_phone` VARCHAR(45) NULL,
                                                `nickname` VARCHAR(45) NULL,
                                                PRIMARY KEY (`id`))
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`contact` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`student` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`student` (
                                                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                `authentication_id` INT UNSIGNED NOT NULL,
                                                `contact_id` INT UNSIGNED NOT NULL,
                                                PRIMARY KEY (`id`),
                                                CONSTRAINT `fk_student_authentication1`
                                                    FOREIGN KEY (`authentication_id`)
                                                        REFERENCES `misdb`.`authentication` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_student_contact1`
                                                    FOREIGN KEY (`contact_id`)
                                                        REFERENCES `misdb`.`contact` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idstudent_UNIQUE` ON `misdb`.`student` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_student_authentication1_idx` ON `misdb`.`student` (`authentication_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_student_contact1_idx` ON `misdb`.`student` (`contact_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`trainer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`trainer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`trainer` (
                                                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                `authentication_id` INT UNSIGNED NOT NULL,
                                                `contact_id` INT UNSIGNED NOT NULL,
                                                PRIMARY KEY (`id`),
                                                CONSTRAINT `fk_trainer_authentication1`
                                                    FOREIGN KEY (`authentication_id`)
                                                        REFERENCES `misdb`.`authentication` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_trainer_contact1`
                                                    FOREIGN KEY (`contact_id`)
                                                        REFERENCES `misdb`.`contact` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idstudent_UNIQUE` ON `misdb`.`trainer` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_trainer_authentication1_idx` ON `misdb`.`trainer` (`authentication_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_trainer_contact1_idx` ON `misdb`.`trainer` (`contact_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`term_period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`term_period` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`term_period` (
                                                    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                    `year` INT NULL,
                                                    `code` VARCHAR(2) NULL,
                                                    `start_date` DATE NULL,
                                                    `end_date` DATE NULL,
                                                    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`course` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`course` (
                                               `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                               `subject` VARCHAR(255) NULL,
                                               PRIMARY KEY (`id`))
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`course` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`batch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`batch` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`batch` (
                                              `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                              `name` VARCHAR(255) NULL,
                                              `trainer_id_trainer` INT UNSIGNED NOT NULL,
                                              `term_period_id` INT UNSIGNED NOT NULL,
                                              `cost` INT NULL,
                                              `course_id` INT UNSIGNED NOT NULL,
                                              PRIMARY KEY (`id`),
                                              CONSTRAINT `fk_course_trainer1`
                                                  FOREIGN KEY (`trainer_id_trainer`)
                                                      REFERENCES `misdb`.`trainer` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_course_term_period1`
                                                  FOREIGN KEY (`term_period_id`)
                                                      REFERENCES `misdb`.`term_period` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_batch_course1`
                                                  FOREIGN KEY (`course_id`)
                                                      REFERENCES `misdb`.`course` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `misdb`.`batch` (`name` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_course_trainer1_idx` ON `misdb`.`batch` (`trainer_id_trainer` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_course_term_period1_idx` ON `misdb`.`batch` (`term_period_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_batch_course1_idx` ON `misdb`.`batch` (`course_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`batch` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`center_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`center_site` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`center_site` (
                                                    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                    `name` VARCHAR(45) NULL,
                                                    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`center_site` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`admin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`admin` (
                                              `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                              `authentication_id` INT UNSIGNED NOT NULL,
                                              `center_site_id` INT UNSIGNED NOT NULL,
                                              `contact_id` INT UNSIGNED NOT NULL,
                                              PRIMARY KEY (`id`),
                                              CONSTRAINT `fk_admin_authentication`
                                                  FOREIGN KEY (`authentication_id`)
                                                      REFERENCES `misdb`.`authentication` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_admin_center_site1`
                                                  FOREIGN KEY (`center_site_id`)
                                                      REFERENCES `misdb`.`center_site` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_admin_contact1`
                                                  FOREIGN KEY (`contact_id`)
                                                      REFERENCES `misdb`.`contact` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idstudent_UNIQUE` ON `misdb`.`admin` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_admin_authentication_idx` ON `misdb`.`admin` (`authentication_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_admin_center_site1_idx` ON `misdb`.`admin` (`center_site_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_admin_contact1_idx` ON `misdb`.`admin` (`contact_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`student_in_batch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`student_in_batch` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`student_in_batch` (
                                                         `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                         `student_id` INT UNSIGNED NOT NULL,
                                                         `course_id` INT UNSIGNED NOT NULL,
                                                         PRIMARY KEY (`id`),
                                                         CONSTRAINT `fk_student_has_course_student1`
                                                             FOREIGN KEY (`student_id`)
                                                                 REFERENCES `misdb`.`student` (`id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_student_has_course_course1`
                                                             FOREIGN KEY (`course_id`)
                                                                 REFERENCES `misdb`.`batch` (`id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_student_has_course_course1_idx` ON `misdb`.`student_in_batch` (`course_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_student_has_course_student1_idx` ON `misdb`.`student_in_batch` (`student_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`student_in_batch` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`payment_method` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`payment_method` (
                                                       `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(45) NULL,
                                                       PRIMARY KEY (`id`))
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`payment_method` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`payment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`payment` (
                                                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                `amount` INT NULL,
                                                `received` DATE NULL,
                                                `payment_method_id` INT UNSIGNED NOT NULL,
                                                PRIMARY KEY (`id`),
                                                CONSTRAINT `fk_payment_payment_method1`
                                                    FOREIGN KEY (`payment_method_id`)
                                                        REFERENCES `misdb`.`payment_method` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_payment_payment_method1_idx` ON `misdb`.`payment` (`payment_method_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`payment` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`batch_has_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`batch_has_payment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`batch_has_payment` (
                                                          `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                          `payment_id` INT UNSIGNED NOT NULL,
                                                          `student_in_batch_id` INT UNSIGNED NOT NULL,
                                                          PRIMARY KEY (`id`),
                                                          CONSTRAINT `fk_course_has_payment_payment1`
                                                              FOREIGN KEY (`payment_id`)
                                                                  REFERENCES `misdb`.`payment` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION,
                                                          CONSTRAINT `fk_batch_has_payment_student_in_batch1`
                                                              FOREIGN KEY (`student_in_batch_id`)
                                                                  REFERENCES `misdb`.`student_in_batch` (`id`)
                                                                  ON DELETE NO ACTION
                                                                  ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_course_has_payment_payment1_idx` ON `misdb`.`batch_has_payment` (`payment_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`batch_has_payment` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_batch_has_payment_student_in_batch1_idx` ON `misdb`.`batch_has_payment` (`student_in_batch_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`attendance` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`attendance` (
                                                   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                   `attended` TINYINT NULL,
                                                   `contact_id` INT UNSIGNED NOT NULL,
                                                   PRIMARY KEY (`id`),
                                                   CONSTRAINT `fk_attendance_course1`
                                                       FOREIGN KEY (`id`)
                                                           REFERENCES `misdb`.`batch` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_attendance_contact1`
                                                       FOREIGN KEY (`contact_id`)
                                                           REFERENCES `misdb`.`contact` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_attendance_course1_idx` ON `misdb`.`attendance` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_attendance_contact1_idx` ON `misdb`.`attendance` (`contact_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`holidays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`holidays` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`holidays` (
                                                 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(45) NULL,
                                                 `term_period_id` INT UNSIGNED NOT NULL,
                                                 PRIMARY KEY (`id`),
                                                 CONSTRAINT `fk_holidays_term_period1`
                                                     FOREIGN KEY (`term_period_id`)
                                                         REFERENCES `misdb`.`term_period` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_holidays_term_period1_idx` ON `misdb`.`holidays` (`term_period_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`holidays` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`exam` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`exam` (
                                             `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                             `name` INT NULL,
                                             `course_id` INT UNSIGNED NOT NULL,
                                             `score_cut_off` INT NULL,
                                             `examcol` VARCHAR(45) NULL,
                                             PRIMARY KEY (`id`),
                                             CONSTRAINT `fk_exam_course1`
                                                 FOREIGN KEY (`course_id`)
                                                     REFERENCES `misdb`.`course` (`id`)
                                                     ON DELETE NO ACTION
                                                     ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_exam_course1_idx` ON `misdb`.`exam` (`course_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`exam_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`exam_results` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`exam_results` (
                                                     `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                     `exam_id` INT UNSIGNED NOT NULL,
                                                     `student_has_course_student_id` INT UNSIGNED NOT NULL,
                                                     `student_has_course_course_id` INT UNSIGNED NOT NULL,
                                                     `score` INT NULL,
                                                     `pass` TINYINT NULL,
                                                     PRIMARY KEY (`id`),
                                                     CONSTRAINT `fk_exam_results_exam1`
                                                         FOREIGN KEY (`exam_id`)
                                                             REFERENCES `misdb`.`exam` (`id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_exam_results_student_has_course1`
                                                         FOREIGN KEY (`id`)
                                                             REFERENCES `misdb`.`student_in_batch` (`id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_exam_results_exam1_idx` ON `misdb`.`exam_results` (`exam_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`exam_results` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`employer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`employer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`employer` (
                                                 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(255) NULL,
                                                 `contact_id` INT UNSIGNED NOT NULL,
                                                 PRIMARY KEY (`id`),
                                                 CONSTRAINT `fk_employer_contact1`
                                                     FOREIGN KEY (`contact_id`)
                                                         REFERENCES `misdb`.`contact` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_employer_contact1_idx` ON `misdb`.`employer` (`contact_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`employer` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `misdb`.`placement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `misdb`.`placement` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `misdb`.`placement` (
                                                  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                  `employer_id` INT UNSIGNED NOT NULL,
                                                  `student_id` INT UNSIGNED NOT NULL,
                                                  PRIMARY KEY (`id`),
                                                  CONSTRAINT `fk_placement_employer1`
                                                      FOREIGN KEY (`employer_id`)
                                                          REFERENCES `misdb`.`employer` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_placement_student1`
                                                      FOREIGN KEY (`student_id`)
                                                          REFERENCES `misdb`.`student` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_placement_employer1_idx` ON `misdb`.`placement` (`employer_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_placement_student1_idx` ON `misdb`.`placement` (`student_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `misdb`.`placement` (`id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
